server:
  # 指定该Eureka实例的端口
  port: 9000
  
spring:
  application:
    name: zuul-gateway
  datasource:
    url: jdbc:mysql://192.168.1.3:3306/shishan?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
eureka:
  instance:
    # 指定该Eureka实例的主机名
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 3
    leaseRenewalIntervalInSeconds: 3
      
zuul:
  retryable: true